version: "3"
services:
  apache:
    build: ./apache
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www:/var/www/html